select database();
SELECT COUNT(*) FROM customer;

--Q1. What is the total revenue generated by male vs. female customers?
select gender, SUM(purchase_amount) as revenue
from customer
group by gender

SELECT COUNT(DISTINCT gender) FROM customer;

--Q2. Which customers used a discount but still spent more than the average purchase amount? 
select customer_id, purchase_amount 
from customer 
where discount_applied = 'Yes' and purchase_amount >= (select AVG(purchase_amount) from customer)

-- Q3. Which are the top 5 products with the highest average review rating?

select 
	item_purchased, 
	round(avg(review_rating),2) AS avg_product_rating
from customer
group by item_purchased
order by avg_product_rating 
Desc
Limit 5;

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 

select 
	shipping_type,
	round(AVG(purchase_amount),2) as avg_purchase_amount
from customer
where shipping_type IN ('Standard','Express')
Group by shipping_type;

--Q5. Do subscribed customers spend more?

select 
	subscription_status,
	Count(customer_id) AS total_customers,
	Round(AVG(purchase_amount), 2) as AVG_spend,
	Round(AVG(purchase_amount), 2) as total_revenue
from customer
group by subscription_status
order by total_revenue Desc;

--Q6. Which products had the highest percentage of discounted purchases?

select
	item_purchased,
	round(
		100.0*sum(case when discount_applied = 'Yes' Then 1 else 0 end),2)
		as discount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 5;

--Q7. Customer Segmentation (New, Returning, Loyal)

WITH customer_type AS (
    SELECT
        customer_id,
        previous_purchases,
        CASE
            WHEN previous_purchases = 1 THEN 'New'
            WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
            ELSE 'Loyal'
        END AS customer_segment
    FROM customer
)
SELECT
    customer_segment,
    COUNT(*) AS number_of_customers
FROM customer_type
GROUP BY customer_segment;


--Q8. Top 3 Products Per Category

WITH item_counts AS (
    SELECT
        category,
        item_purchased,
        COUNT(customer_id) AS total_orders,
        ROW_NUMBER() OVER (
            PARTITION BY category
            ORDER BY COUNT(customer_id) DESC
        ) AS item_rank
    FROM customer
    GROUP BY category, item_purchased
)
SELECT
    category,
    item_purchased,
    total_orders
FROM item_counts
WHERE item_rank <= 3;

--Q9. Repeat Buyers & Subscription Status eg: Repeat buyer = a customer with previous_purchases > 5 (example threshold)

SELECT
    subscription_status,
    COUNT(customer_id) AS repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;

--Q10. Total Revenue by Age Group

SELECT 
    age_group,
    SUM(purchase_amount) AS total_revenue
FROM (
    SELECT 
        CASE
            WHEN age < 25 THEN 'Under 25'
            WHEN age BETWEEN 25 AND 34 THEN '25-34'
            WHEN age BETWEEN 35 AND 44 THEN '35-44'
            ELSE '45+'
        END AS age_group,
        purchase_amount
    FROM customer
) AS t
GROUP BY age_group
ORDER BY total_revenue DESC;





		



